# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

version: 2

project_name: ocimage

before:
  hooks:
    - make precommit

builds:
  - main: .
    binary: ocimage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/podplane/ocimage/internal/buildvars.buildVersion={{ .Tag }}
      - -X github.com/podplane/ocimage/internal/buildvars.buildDate={{ .Date }}
      - -X github.com/podplane/ocimage/internal/buildvars.commitHash={{ .ShortCommit }}
      - -X github.com/podplane/ocimage/internal/buildvars.commitDate={{ .CommitDate }}
      - -X github.com/podplane/ocimage/internal/buildvars.commitBranch={{ .Branch }}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha512

signs:
  - artifacts: checksum
    cmd: cosign
    signature: '${artifact}.bundle'
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    output: true

sboms:
  - id: archive
    artifacts: archive
    documents:
      - '{{ .ArtifactName }}.spdx.json'
  - id: binary
    artifacts: binary
    documents:
      - '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_{{ .Binary }}.spdx.json'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: podplane
    name: ocimage
  draft: false
  prerelease: auto
  replace_existing_artifacts: false

brews:
  - name: ocimage
    repository:
      owner: podplane
      name: homebrew-tap
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    commit_author:
      name: podplane-release-bot
      email: release-bot@podplane.dev
    homepage: 'https://github.com/podplane/ocimage'
    description: 'Build, tag, & push container images. No runtime dependencies.'
    license: 'Apache-2.0'
