# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

FROM reg.mini.dev/bun:v1

ENV NODE_ENV=production \
    PORT=8080

WORKDIR /app

COPY demo/.output .

CMD ["bun", "server/index.mjs"]
