// Podplane <https://podplane.dev>
// Copyright The Podplane Authors
// SPDX-License-Identifier: Apache-2.0

package initfile

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/podplane/ocimage/examples"
)

// Template describes a generated packaging template.
type Template struct {
	ID          string
	Name        string
	Description string
	Files       []TemplateFile
}

// TemplateFile describes a file generated by a template.
type TemplateFile struct {
	Path   string
	Source string
}

// Match describes a template detected for a project directory.
type Match struct {
	Template Template
	Reason   string
}

var templates = []Template{
	{ID: "csharp-aspnet-chiseled", Name: "C# ASP.NET chiseled", Description: "Package a prebuilt ASP.NET app on the .NET chiseled runtime", Files: []TemplateFile{{Path: "Containerfile", Source: "csharp/aspnet-chiseled/Containerfile"}}},
	{ID: "go-scratch-chi", Name: "Go scratch", Description: "Package a prebuilt Go Linux binary", Files: []TemplateFile{{Path: "Containerfile", Source: "go/scratch-chi/Containerfile"}}},
	{ID: "php-laravel", Name: "PHP Laravel", Description: "Package a prebuilt Laravel app on the ocimage PHP base", Files: []TemplateFile{{Path: "Containerfile", Source: "php/laravel/Containerfile"}}},
	{ID: "python-django", Name: "Python Django", Description: "Package a prebuilt Django app on the ocimage Python base", Files: []TemplateFile{{Path: "Containerfile", Source: "python/django/Containerfile"}}},
	{ID: "ruby-rails", Name: "Ruby Rails", Description: "Package a prebuilt Rails app on the ocimage Ruby base", Files: []TemplateFile{{Path: "Containerfile", Source: "ruby/ruby-rails/Containerfile"}}},
	{ID: "rust-scratch", Name: "Rust scratch", Description: "Package a prebuilt Rust Linux binary", Files: []TemplateFile{{Path: "Containerfile", Source: "rust/scratch/Containerfile"}}},
	{ID: "typescript-hono-bun", Name: "TypeScript Hono on Bun", Description: "Package a prebuilt Hono server for Bun", Files: []TemplateFile{{Path: "Containerfile", Source: "typescript/hono/Containerfile.bun"}}},
	{ID: "typescript-hono-node", Name: "TypeScript Hono on Node.js", Description: "Package a prebuilt Hono server for Node.js", Files: []TemplateFile{{Path: "Containerfile", Source: "typescript/hono/Containerfile.node"}}},
	{ID: "typescript-tanstack-start-bun", Name: "TypeScript TanStack Start on Bun", Description: "Package a prebuilt TanStack Start server for Bun", Files: []TemplateFile{{Path: "Containerfile", Source: "typescript/fullstack-tanstack-start/Containerfile.bun"}}},
	{ID: "typescript-tanstack-start-node", Name: "TypeScript TanStack Start on Node.js", Description: "Package a prebuilt TanStack Start server for Node.js", Files: []TemplateFile{{Path: "Containerfile", Source: "typescript/fullstack-tanstack-start/Containerfile.node"}}},
	{ID: "typescript-tanstack-start-spa", Name: "TypeScript TanStack Start SPA", Description: "Package a prebuilt static TanStack Start app with Caddy", Files: []TemplateFile{{Path: "Containerfile", Source: "typescript/spa-tanstack-start/Containerfile"}, {Path: "Caddyfile", Source: "typescript/spa-tanstack-start/Caddyfile"}}},
}

// Templates returns the built-in templates available for generation.
func Templates() []Template {
	return slices.Clone(templates)
}

// FindTemplate returns the template for id.
func FindTemplate(id string) (Template, bool) {
	idx := slices.IndexFunc(templates, func(tmpl Template) bool {
		return tmpl.ID == id
	})
	if idx < 0 {
		return Template{}, false
	}
	return templates[idx], true
}

// Detect returns built-in templates that match files in dir.
func Detect(dir string) ([]Match, error) {
	var matches []Match
	add := func(id, reason string) {
		tmpl, ok := FindTemplate(id)
		if ok {
			matches = append(matches, Match{Template: tmpl, Reason: reason})
		}
	}

	if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
		add("go-scratch-chi", "go.mod found")
	}
	if _, err := os.Stat(filepath.Join(dir, "Cargo.toml")); err == nil {
		add("rust-scratch", "Cargo.toml found")
	}
	if hasCSharpWebProject(dir) {
		add("csharp-aspnet-chiseled", "ASP.NET project files found")
	}
	if _, err := os.Stat(filepath.Join(dir, "artisan")); strings.Contains(readFile(filepath.Join(dir, "composer.json")), "laravel/framework") || err == nil {
		add("php-laravel", "Laravel project files found")
	}
	if _, err := os.Stat(filepath.Join(dir, "manage.py")); err == nil || fileContainsFold(filepath.Join(dir, "requirements.txt"), "django") || fileContainsFold(filepath.Join(dir, "pyproject.toml"), "django") {
		add("python-django", "Django project files found")
	}
	if _, err := os.Stat(filepath.Join(dir, "config", "application.rb")); strings.Contains(readFile(filepath.Join(dir, "Gemfile")), "rails") || err == nil {
		add("ruby-rails", "Rails project files found")
	}

	pkg, err := readPackageJSON(filepath.Join(dir, "package.json"))
	if err != nil {
		return nil, err
	}
	if pkg != nil {
		bun := slices.ContainsFunc([]string{"bun.lock", "bun.lockb"}, func(name string) bool {
			_, err := os.Stat(filepath.Join(dir, name))
			return err == nil
		})
		node := slices.ContainsFunc([]string{"package-lock.json", "yarn.lock", "pnpm-lock.yaml"}, func(name string) bool {
			_, err := os.Stat(filepath.Join(dir, name))
			return err == nil
		})
		if packageHas(pkg, "hono") {
			addRuntimeMatches(add, "typescript-hono", bun, node)
		}
		if packageHas(pkg, "@tanstack/react-start") || packageHas(pkg, "@tanstack/start") {
			if packageHas(pkg, "@vitejs/plugin-react") || packageHas(pkg, "vite") {
				add("typescript-tanstack-start-spa", "TanStack Start package.json found")
			}
			addRuntimeMatches(add, "typescript-tanstack-start", bun, node)
		}
	}

	return matches, nil
}

// Write writes template files into dir. Existing files are not overwritten unless overwrite is true.
func Write(dir string, tmpl Template, overwrite bool) ([]string, error) {
	var written []string
	for _, file := range tmpl.Files {
		body, err := examples.Files.ReadFile(file.Source)
		if err != nil {
			return nil, fmt.Errorf("read embedded %s: %w", file.Source, err)
		}
		target := filepath.Join(dir, file.Path)
		if !overwrite {
			if _, err := os.Stat(target); err == nil {
				return nil, fmt.Errorf("%s already exists; pass --force to overwrite", file.Path)
			} else if !os.IsNotExist(err) {
				return nil, fmt.Errorf("check %s: %w", file.Path, err)
			}
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return nil, fmt.Errorf("create %s parent: %w", file.Path, err)
		}
		if err := os.WriteFile(target, body, 0o644); err != nil {
			return nil, fmt.Errorf("write %s: %w", file.Path, err)
		}
		written = append(written, file.Path)
	}
	return written, nil
}

// addRuntimeMatches adds Bun or Node.js runtime variants based on detected lockfiles.
func addRuntimeMatches(add func(string, string), prefix string, bun bool, node bool) {
	switch {
	case bun && !node:
		add(prefix+"-bun", "package.json and Bun lockfile found")
	case node && !bun:
		add(prefix+"-node", "package.json and Node.js lockfile found")
	default:
		add(prefix+"-bun", "package.json found; runtime not uniquely detected")
		add(prefix+"-node", "package.json found; runtime not uniquely detected")
	}
}

// hasCSharpWebProject reports whether dir looks like an ASP.NET project.
func hasCSharpWebProject(dir string) bool {
	matches, err := filepath.Glob(filepath.Join(dir, "*.csproj"))
	if err == nil && slices.ContainsFunc(matches, func(match string) bool {
		return strings.Contains(readFile(match), "Microsoft.NET.Sdk.Web")
	}) {
		return true
	}
	program := readFile(filepath.Join(dir, "Program.cs"))
	return strings.Contains(program, "WebApplication.CreateBuilder") || strings.Contains(program, "MapGet") || strings.Contains(program, "MapControllers")
}

// readFile returns the file contents or an empty string if the file cannot be read.
func readFile(path string) string {
	body, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(body)
}

// fileContainsFold reports whether path contains needle, ignoring ASCII case.
func fileContainsFold(path string, needle string) bool {
	return strings.Contains(strings.ToLower(readFile(path)), strings.ToLower(needle))
}

type packageJSON struct {
	Dependencies         map[string]string `json:"dependencies"`
	DevDependencies      map[string]string `json:"devDependencies"`
	OptionalDependencies map[string]string `json:"optionalDependencies"`
}

// readPackageJSON reads the subset of package.json needed for detection.
func readPackageJSON(path string) (*packageJSON, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read package.json: %w", err)
	}
	var pkg packageJSON
	if err := json.Unmarshal(body, &pkg); err != nil {
		return nil, fmt.Errorf("parse package.json: %w", err)
	}
	return &pkg, nil
}

// packageHas reports whether package.json declares a dependency by name.
func packageHas(pkg *packageJSON, name string) bool {
	return slices.ContainsFunc([]map[string]string{pkg.Dependencies, pkg.DevDependencies, pkg.OptionalDependencies}, func(deps map[string]string) bool {
		_, ok := deps[name]
		return ok
	})
}
