# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

FROM reg.mini.dev/caddy:v2

ENV PORT=8080

COPY Caddyfile /etc/caddy/Caddyfile
COPY demo/dist /usr/share/caddy
