# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

ARG OCIMAGE_STORE_URL=
FROM ${OCIMAGE_STORE_URL}python/base:3.14

ENV DJANGO_SETTINGS_MODULE=config.settings \
    PORT=8080

WORKDIR /app

COPY --chown=nonroot:nonroot demo/manage.py ./
COPY --chown=nonroot:nonroot demo/config config
COPY --chown=nonroot:nonroot demo/tasks tasks
COPY --chown=nonroot:nonroot demo/staticfiles staticfiles

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "config.wsgi:application"]
