# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: binary
          skip-cache: true

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.21.0

      - name: Install cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Generate Homebrew tap token
        id: homebrew-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 3948556
          private-key: ${{ secrets.HOMEBREW_TAP_APP_PRIVATE_KEY }}
          owner: podplane
          repositories: homebrew-tap

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.homebrew-token.outputs.token }}
